<?php

namespace App\Exceptions;

use App\Http\Controllers\Traits\ResponseTrait;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Response;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    public function render($request, Throwable $e)
    {
        if ($request->expectsJson()) {
            if ($e instanceof ModelNotFoundException) {
                return response()->json([
                    "status" => Response::HTTP_NOT_FOUND,
                    "message" => "Data is not found."
                ], Response::HTTP_NOT_FOUND);
            }
            if ($e instanceof \Illuminate\Validation\ValidationException) {
                return ResponseTrait::sendValidationErrors($e->errors(), $e->getMessage());
            }
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
